-- Join the Customers table with the Orders table to list all orders made by a specific customer.
SELECT c.customer_id, c.first_name, c.last_name,
       o.order_id, o.order_date, o.total_amount, o.shipping_address
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE c.customer_id = 1;

-- Find all orders placed by customers who live in a specific city (using the address field in Customers table).
SELECT c.customer_id, c.first_name, o.order_id, o.shipping_address
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE c.address LIKE '%Hyderabad%';

-- List the products and their categories by joining the Products and Categories tables.
SELECT p.product_id, p.name, c.category_name
FROM Products p
JOIN Categories c ON p.category_id = c.category_id;

-- Get a list of all products purchased by a particular customer, including their name, description, and quantity ordered (using Orders, Order_Items, and Products).
SELECT c.first_name, p.name, p.description, oi.quantity
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE c.customer_id = 1;

-- Join Order_Items with Orders to get a list of all products ordered along with the order's total amount.
SELECT o.order_id, p.name, oi.quantity, o.total_amount
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id;

-- Find the total number of items ordered for each product (using Order_Items and Products).
SELECT p.product_id, p.name, SUM(oi.quantity) AS total_items
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.name;

-- Find the customer who placed the highest value order (using Orders and Customers).
SELECT c.customer_id, c.first_name, o.order_id, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
ORDER BY o.total_amount DESC
LIMIT 1;

-- Get a list of all customers who ordered a specific product (join Customers, Orders, and Order_Items).
SELECT DISTINCT c.customer_id, c.first_name
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE oi.product_id = 1;

-- Join Products and Order_Items to find the total revenue generated by each product.
SELECT p.product_id, p.name,
       SUM(oi.quantity * oi.item_price) AS total_revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.name;

-- Find the most popular product in each category (using Products, Order_Items, and Categories).
SELECT c.category_name, p.name, SUM(oi.quantity) AS total_sold
FROM Categories c
JOIN Products p ON c.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.category_name, p.name
HAVING SUM(oi.quantity) = (
    SELECT MAX(total_qty)
    FROM (
        SELECT SUM(oi2.quantity) AS total_qty
        FROM Products p2
        JOIN Order_Items oi2 ON p2.product_id = oi2.product_id
        WHERE p2.category_id = p.category_id
        GROUP BY p2.product_id
    ) sub
);

-- Get a list of all orders with their corresponding products, including product name and quantity ordered (using Orders, Order_Items, and Products).
SELECT o.order_id, p.name, oi.quantity
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id;

-- Find the average number of items ordered per customer (using Orders and Order_Items).
SELECT c.customer_id, AVG(total_items) AS avg_items
FROM (
    SELECT o.customer_id, SUM(oi.quantity) AS total_items
    FROM Orders o
    JOIN Order_Items oi ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
) t
JOIN Customers c ON c.customer_id = t.customer_id
GROUP BY c.customer_id;

-- List customers who have not placed any orders (using Customers and Orders).
SELECT c.customer_id, c.first_name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Find all orders that contain more than 5 items, including customer details (using Orders, Order_Items, and Customers).
SELECT o.order_id, c.first_name, c.last_name, SUM(oi.quantity) AS total_items
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, c.first_name, c.last_name
HAVING SUM(oi.quantity) > 5;

-- List the total number of products sold per category (using Products, Order_Items, and Categories).
SELECT c.category_name, SUM(oi.quantity) AS total_products_sold
FROM Categories c
JOIN Products p ON c.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.category_name;

-- Find all orders placed in the last 30 days along with the products purchased (using Orders, Order_Items, and Products).
SELECT o.order_id, p.name, oi.quantity, o.order_date
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL 30 DAY;

-- Get a list of products that are out of stock and were previously ordered (using Products and Order_Items).
SELECT DISTINCT p.product_id, p.name
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
WHERE p.stock_quantity = 0;

-- List the products that have not been sold in the last 6 months (using Products and Order_Items).
SELECT p.product_id, p.name
FROM Products p
WHERE p.product_id NOT IN (
    SELECT oi.product_id
    FROM Order_Items oi
    JOIN Orders o ON oi.order_id = o.order_id
    WHERE o.order_date >= CURRENT_DATE - INTERVAL 6 MONTH
);

-- Find customers who have placed orders above a certain value threshold, with order details (using Orders, Customers).
-- threshold = 1000
SELECT c.customer_id, c.first_name, o.order_id, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.total_amount > 1000;

-- Get the total sales amount for each customer, including their personal details (using Orders, Order_Items, and Customers).
SELECT c.customer_id, c.first_name, c.last_name,SUM(o.total_amount) AS total_sales
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;

