-- Join the Customers table with the Orders table to list all orders made by a specific customer.
select * from Customers c join Orders o on c.customer_id=o.customer_id;

-- Find all orders placed by customers who live in a specific city (using the address field in Customers table).
select * from Customers c join Orders o on c.customer_id=o.customer_id where c.address like %Hyderabad%;

-- List the products and their categories by joining the Products and Categories tables.
select p.name, c.category_name from Products p join Categories c on p.category_id=c.category_id;

-- Get a list of all products purchased by a particular customer, including their name, description, and quantity ordered (using Orders, Order_Items, and Products).
select * from p.name, p.description, oi.quantity from Customers c join Orders o
on c.customer_id=o.customer_id 
join Order_Items oi on o.order_id=oi.order_id
join Products p on oi.product_id=p.product_id
where c.customer_id=1;

-- Join Order_Items with Orders to get a list of all products ordered along with the order's total amount.
select oi.product_id,o.total_amount from Order_Items oi 
join Orders o on oi.order_id=o.order_id;

-- Find the total number of items ordered for each product (using Order_Items and Products).
select p.name, sum(oi.quantity) as total_items_ordered from Products p  join Order_Items oi on oi.product_id=p.product_id group by p.name;

-- Find the customer who placed the highest value order (using Orders and Customers).
select c.first_name,c.last_name, o.total_amount from Orders o 
join Customers c on o.customer_id=c.customer_id order by o.total_amount desc limit 1;

-- Get a list of all customers who ordered a specific product (join Customers, Orders, and Order_Items).
select distinct c.* from Customers c join Orders o on c.customer_id=o.customer_id
join Order_Items oi on o.order_id=oi.order_id
where oi.product_id=1;

-- Join Products and Order_Items to find the total revenue generated by each product.
select p.name, sum(oi.quantity * oi.item_price) as revenue from Products p 
join Order_Items oi on p.product_id=oi.product_id 
group by p.name;

-- Find the most popular product in each category (using Products, Order_Items, and Categories).
SELECT c.category_name, p.name, SUM(oi.quantity) AS total_sold
FROM Products p
JOIN Categories c ON p.category_id = c.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.category_name, p.name
HAVING SUM(oi.quantity) = (
    SELECT MAX(total_qty)
    FROM (
        SELECT SUM(oi2.quantity) AS total_qty
        FROM Products p2
        JOIN Order_Items oi2 ON p2.product_id = oi2.product_id
        WHERE p2.category_id = p.category_id
        GROUP BY p2.product_id
    ) sub
);

-- Get a list of all orders with their corresponding products, including product name and quantity ordered (using Orders, Order_Items, and Products).
select o.order_id, p.name,oi.quantity from Orders o join Order_Items oi on o.order_id=oi.order_id
join Products p on oi.product_id=p.product_id;

-- Find the average number of items ordered per customer (using Orders and Order_Items).
SELECT c.customer_id, AVG(oi.quantity) AS avg_items
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id;

-- List customers who have not placed any orders (using Customers and Orders).
select * from Customers c left join Orders o on c.customer_id=o.customer_id
where o.order_id is null;

-- Find all orders that contain more than 5 items, including customer details (using Orders, Order_Items, and Customers).
SELECT c.*, o.order_id, SUM(oi.quantity) AS total_items
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, c.customer_id
HAVING SUM(oi.quantity) > 5;

-- List the total number of products sold per category (using Products, Order_Items, and Categories).
SELECT c.category_name, SUM(oi.quantity) AS total_sold
FROM Categories c
JOIN Products p ON c.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.category_name;

-- Find all orders placed in the last 30 days along with the products purchased (using Orders, Order_Items, and Products).
SELECT o.order_id, p.name, oi.quantity
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE o.order_date >= CURRENT_DATE - INTERVAL 30 DAY;

-- Get a list of products that are out of stock and were previously ordered (using Products and Order_Items).
SELECT DISTINCT p.*
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
WHERE p.stock_quantity = 0;

-- List the products that have not been sold in the last 6 months (using Products and Order_Items).
SELECT p.*
FROM Products p
WHERE p.product_id NOT IN (
    SELECT oi.product_id
    FROM Order_Items oi
    JOIN Orders o ON oi.order_id = o.order_id
    WHERE o.order_date >= CURRENT_DATE - INTERVAL 6 MONTH
);

-- Find customers who have placed orders above a certain value threshold, with order details (using Orders, Customers).
SELECT c.*, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.total_amount > 1000;

-- Get the total sales amount for each customer, including their personal details (using Orders, Order_Items, and Customers).
SELECT c.customer_id, c.first_name, c.last_name,
       SUM(o.total_amount) AS total_sales
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;


